### ISSUE TITLE
RSS Feed Needs review

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/lab-site#198]
The RSS Feed is there but needs some review.

- [ ] What description should it have?
- [ ] Should there be an excerpt or what?
- [ ] Which content should go in there?
- [x] Should there be a DE and EN version (currently DE/EN is in the same feed)?

Currently it is here https://lab.technologiestiftung-berlin.de/feed.xml
And looks like this in an RSS Feed Reader

<img width="1552" alt="Screenshot 2020-01-09 at 14 32 35" src="https://user-images.githubusercontent.com/315106/72071827-f4dcc080-32ec-11ea-8ffd-bdbe678c1cc3.png">

related to #10

**Comment by fabianmoronzirfas** [comment]
The source for the feed is [here -> source/feed.xml](https://github.com/technologiestiftung/lab-site/blob/master/source/feed.xml)

And some values need to be set in _config.yml

- Description needs to be set: https://github.com/technologiestiftung/lab-site/blob/master/_config.yml#L23
- `site.name` is missing

**Comment by tori-d** [comment]
From my perspective, the feed should publish all published projects (i.e. everything here https://lab.technologiestiftung-berlin.de/projects/de/). Right now it's also grabbing pages that are not yet set to be visible, which is obviously not ideal. 

re: excerpts – is it easily done to show the first 1-2 paragraphs? Because then I would go that route. 

Can DE & EN be easily separated into two feeds? otherwise I don't find it the end of the world to have it all bundled in one.

**Comment by fabianmoronzirfas** [comment]
In PR #199 I fixed

- only visible are shown
- separation between EN/DE
- description
- site.name

**Comment by fabianmoronzirfas** [comment]
> re: excerpts – is it easily done to show the first 1-2 paragraphs? Because then I would go that route.

If we want a excerpt we need to set it manually, I can truncate the content to the first 50 words though.

**Comment by fabianmoronzirfas** [comment]
Added a little hack to add excerpts. If you add somewhere a 

```html
<!--more-->
```

It will use everything before it as an excerpt/description. If not it will truncate after 50 words.

**Comment by fabianmoronzirfas** [comment]
See [EN](https://deploy-preview-199--tsb-labsite.netlify.com/en/feed.xml) and [DE](https://deploy-preview-199--tsb-labsite.netlify.com/feed.xml)

**Comment by bnjmnsbl** [comment]
LGTM
